ci: remove macos build
The environment was building the 'github:hraban/mac-app-util' which depends on on list sources that are no longer avialable:

       last 10 log lines:
       >
       > trying https://gitlab.common-lisp.net/api/v4/projects/iterate%2Fiterate/repository/archive.tar.gz?sha=26cf129a03b45d6dd7d2a659622244d20a9ab6f5
       >   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
       >                                  Dload  Upload   Total   Spent    Left  Speed
       > 100  4260    0  4260    0     0  24364      0 --:--:-- --:--:-- --:--:-- 24482
       > unpacking source archive /private/tmp/nix-build-source.drv-0/archive.tar.gz?sha=26cf129a03b45d6dd7d2a659622244d20a9ab6f5
       > tar: This does not look like a tar archive
       > tar: Skipping to next header
       > tar: Exiting with failure status due to previous errors
       > do not know how to unpack source archive /private/tmp/nix-build-source.drv-0/archive.tar.gz?sha=26cf129a03b45d6dd7d2a659622244d20a9ab6f5
       For full logs, run:
         nix log /nix/store/0w283k830n1jn0j3wihhgh6rz99wb2fa-source.drv
error: 1 dependencies of derivation '/nix/store/bvgxpd9i3jawal770739jng3yl4by13h-system-iterate.drv' failed to build
error (ignored): error: cannot unlink /private/tmp/nix-build-system-fare-utils.drv-0/source: Directory not empty
error: 1 dependencies of derivation '/nix/store/pzw9lw6mwr8q9avs63q0sfhp4n5fhvv5-system-iterate.drv' failed to build
error: 1 dependencies of derivation '/nix/store/xn10vzdf2smfj7cnw4jfy0gcjp59b2xn-sbcl-2.4.10.drv' failed to build
error: 1 dependencies of derivation '/nix/store/mcn95qg6ncd2n1hxsx0byihp7d1kpsbh-mac-app-util.drv' failed to build