To revert: push workaround for yq bug
The linked bug is causing this failure in CI:
```
Error: bad file '/home/runner/work/floxenvs/floxenvs/rust/.flox/env/manifest.toml': unsupported type Comment
```